"""redo update on type model

Revision ID: 489241e392f3
Revises: 643b3cd320a1
Create Date: 2022-05-06 12:09:46.317455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '489241e392f3'
down_revision = '643b3cd320a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_types_title'), 'types', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_types_title'), table_name='types')
    # ### end Alembic commands ###
