"""updated type model

Revision ID: 643b3cd320a1
Revises: f397409092e9
Create Date: 2022-05-06 11:34:47.432412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '643b3cd320a1'
down_revision = 'f397409092e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_types_title', table_name='types')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_types_title', 'types', ['title'], unique=False)
    # ### end Alembic commands ###
